apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-app
spec:
  selector:
    matchLabels:
      app: elasticsearch-app
  template:
    metadata:
      labels:
        app: elasticsearch-app
    spec:
      containers:
      - name: elasticsearch-app
        image: elasticsearch-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-map
data:
  ELASTICSEARCH_SERVER: 127.0.0.1
  ELASTICSEARCH_CLUSTER: docker-cluster
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-app
spec:
  type: NodePort
  selector:
    app: elasticsearch-app
  ports:
  - port: 8080
    targetPort: 8080
